In [1]:
import numpy as mp 
import pandas as pd

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [3]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [7]:
df2 = pd.DataFrame(data_list,columns=['Name', 'Age', 'City', 'Salary'])
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [10]:
df2["designation"] = ["Engineer", "Manager", "Analyst", "Director"]

In [11]:
df2

    Name  Age      City  Salary designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000     Manager
2  Peter   29    Berlin   62000     Analyst
3  Linda   42    London   85000    Director

In [15]:
df2.drop("designation", axis = 1,inplace = True)

In [16]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [19]:
df2.loc[[0,1],["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [22]:
df2[(df['Age']>30)&(df['City']== "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000